### ISSUE TITLE
Keygen panic

### ISSUE THREAD

**Issue by tmpfs** [LavaMoat/ecdsa-wasm#42]
```
wasm_pkg_ecdsa_wasm_js.index.js:362 panicked at 'called `Result::unwrap()` on an `Err` value: HandleMessage(MsgOverwrite)', src/gg2020/keygen.rs:37:36

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (http://localhost:8080/wasm_pkg_ecdsa_wasm_js.index.js:350:19)
    at http://localhost:8080/4f8c011425f1d30d7c1b.wasm:wasm-function[833]:0xb907c
    at http://localhost:8080/4f8c011425f1d30d7c1b.wasm:wasm-function[233]:0x8596e
    at http://localhost:8080/4f8c011425f1d30d7c1b.wasm:wasm-function[614]:0xb3deb
    at http://localhost:8080/4f8c011425f1d30d7c1b.wasm:wasm-function[642]:0xb46ab
    at http://localhost:8080/4f8c011425f1d30d7c1b.wasm:wasm-function[482]:0xaac70
    at http://localhost:8080/4f8c011425f1d30d7c1b.wasm:wasm-function[261]:0x9328c
    at Object.keygenHandleIncoming (http://localhost:8080/wasm_pkg_ecdsa_wasm_js.index.js:190:10)
    at callback (http://localhost:8080/vendors-node_modules_comlink_dist_esm_comlink_mjs.index.js:115:48)


imports.wbg.__wbg_error_09919627ac0992f5 @ wasm_pkg_ecdsa_wasm_js.index.js:362
$func833 @ 4f8c011425f1d30d7c1b.wasm:0xb918d
$func233 @ 4f8c011425f1d30d7c1b.wasm:0x8596e
$func614 @ 4f8c011425f1d30d7c1b.wasm:0xb3deb
$func642 @ 4f8c011425f1d30d7c1b.wasm:0xb46ab
$func482 @ 4f8c011425f1d30d7c1b.wasm:0xaac70
$keygenHandleIncoming @ 4f8c011425f1d30d7c1b.wasm:0x9328c
keygenHandleIncoming @ wasm_pkg_ecdsa_wasm_js.index.js:190
callback @ vendors-node_modules_comlink_dist_esm_comlink_mjs.index.js:115
index.js:91498 Uncaught (in promise) RuntimeError: unreachable
    at 4f8c011425f1d30d7c1b.wasm
    at 4f8c011425f1d30d7c1b.wasm
    at 4f8c011425f1d30d7c1b.wasm
    at 4f8c011425f1d30d7c1b.wasm
    at 4f8c011425f1d30d7c1b.wasm
    at 4f8c011425f1d30d7c1b.wasm
    at Object.keygenHandleIncoming (wasm_pkg_ecdsa_wasm_js.index.js:190:10)
    at callback (vendors-node_modules_comlink_dist_esm_comlink_mjs.index.js:115:48)
```

**Comment by tmpfs** [comment]
This appears to have been fixed in https://github.com/LavaMoat/ecdsa-wasm/pull/44/commits/9f39e2dd6bd351eb3ebef182e7b1ee7dd3c92b17.

There was a bug whereby key generation session signup was being triggered multiple times, I am unsure exactly how but by guarding against starting multiple key generation sessions this bug is fixed.
