### ISSUE TITLE
Signing error in Javascript (undefined is not iterable)

### ISSUE THREAD

**Issue by tmpfs** [LavaMoat/ecdsa-wasm#45]
```
console.info:  client2 transition 0 to KEYGEN_ROUND_1
console.info:  client3 transition 0 to KEYGEN_ROUND_1
console.info:  client3 transition 1 from KEYGEN_ROUND_1 to KEYGEN_ROUND_2
console.info:  client3 Got incoming messages with length 2
console.info:  client3 Got incoming messages [Object,Object]
console.info:  client1 transition 1 from KEYGEN_ROUND_1 to KEYGEN_ROUND_2
console.info:  client1 Got incoming messages with length 2
console.info:  client1 Got incoming messages [Object,Object]
console.info:  client2 transition 1 from KEYGEN_ROUND_1 to KEYGEN_ROUND_2
console.info:  client2 Got incoming messages with length 2
console.info:  client2 Got incoming messages [Object,Object]
console.info:  client2 transition 2 from KEYGEN_ROUND_2 to KEYGEN_ROUND_3
console.info:  client2 Got incoming messages with length 2
console.info:  client2 Got incoming messages [Object,Object]
console.info:  client1 transition 2 from KEYGEN_ROUND_2 to KEYGEN_ROUND_3
console.info:  client3 transition 2 from KEYGEN_ROUND_2 to KEYGEN_ROUND_3
console.info:  client1 Got incoming messages with length 2
console.info:  client3 Got incoming messages with length 2
console.info:  client3 Got incoming messages [Object,Object]
console.info:  client1 Got incoming messages [Object,Object]
console.info:  client1 transition 3 from KEYGEN_ROUND_3 to KEYGEN_ROUND_4
console.info:  client1 Got incoming messages with length 2
console.info:  client1 Got incoming messages [Object,Object]
console.info:  client2 transition 3 from KEYGEN_ROUND_3 to KEYGEN_ROUND_4
console.info:  client2 Got incoming messages with length 2
console.info:  client2 Got incoming messages [Object,Object]
console.info:  client3 transition 3 from KEYGEN_ROUND_3 to KEYGEN_ROUND_4
console.info:  client3 Got incoming messages with length 2
console.info:  client3 Got incoming messages [Object,Object]
console.info:  client1 transition 4 from KEYGEN_ROUND_4 to KEYGEN_ROUND_5
console.info:  client2 transition 4 from KEYGEN_ROUND_4 to KEYGEN_ROUND_5
console.info:  client3 transition 4 from KEYGEN_ROUND_4 to KEYGEN_ROUND_5
console.info:  client1 transition 0 to SIGN_ROUND_0
console.info:  client2 transition 0 to SIGN_ROUND_0
console.info:  client1 transition 1 from SIGN_ROUND_0 to SIGN_ROUND_1
console.info:  client2 transition 1 from SIGN_ROUND_0 to SIGN_ROUND_1
console.info:  client1 transition 2 from SIGN_ROUND_1 to SIGN_ROUND_2
console.info:  client2 transition 2 from SIGN_ROUND_1 to SIGN_ROUND_2
console.info:  client2 transition 3 from SIGN_ROUND_2 to SIGN_ROUND_3
unhandled error: client2 undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

**Comment by tmpfs** [comment]
Just reproduced this again:

```
console.info:  client1 %cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools font-weight:bold
console.info:  client1 Rendering keygen component!!!
console.info:  client1 componentDidMount: adding listeners!
console.info:  client2 %cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools font-weight:bold
console.info:  client3 %cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools font-weight:bold
console.info:  client2 Rendering keygen component!!!
console.info:  client2 componentDidMount: adding listeners!
console.info:  client3 Rendering keygen component!!!
console.info:  client3 componentDidMount: adding listeners!
console.info:  client1 Set keygen session {phase: keygen, uuid: 681004bd-32e4-41bc-9ac0-f2b772608032}
console.info:  client2 Got partyNumber from Session.signup 2
console.info:  client3 Got partyNumber from Session.signup 1
console.info:  client3 Set keygen session {phase: keygen, uuid: 681004bd-32e4-41bc-9ac0-f2b772608032, partySignup: Object}
console.info:  client2 Set keygen session {phase: keygen, uuid: 681004bd-32e4-41bc-9ac0-f2b772608032, partySignup: Object}
console.info:  client1 Got partyNumber from Session.signup 3
console.info:  client1 Set keygen session {phase: keygen, uuid: 681004bd-32e4-41bc-9ac0-f2b772608032, partySignup: Object}
console.info:  client1 GOT SESSION SIGNUP EVENT 681004bd-32e4-41bc-9ac0-f2b772608032
console.info:  client2 GOT SESSION SIGNUP EVENT 681004bd-32e4-41bc-9ac0-f2b772608032
console.info:  client3 GOT SESSION SIGNUP EVENT 681004bd-32e4-41bc-9ac0-f2b772608032
  ✘  tests/keygen-sign.spec.mjs:23:1 › create key shares and sign message (30s)
console.info:  client3 transition 0 to KEYGEN_ROUND_1
console.info:  client2 transition 0 to KEYGEN_ROUND_1
console.info:  client1 transition 1 from KEYGEN_ROUND_1 to KEYGEN_ROUND_2
console.info:  client3 transition 1 from KEYGEN_ROUND_1 to KEYGEN_ROUND_2
console.info:  client2 transition 1 from KEYGEN_ROUND_1 to KEYGEN_ROUND_2
console.info:  client2 transition 2 from KEYGEN_ROUND_2 to KEYGEN_ROUND_3
console.info:  client3 transition 2 from KEYGEN_ROUND_2 to KEYGEN_ROUND_3
console.info:  client1 transition 2 from KEYGEN_ROUND_2 to KEYGEN_ROUND_3
console.info:  client3 transition 3 from KEYGEN_ROUND_3 to KEYGEN_ROUND_4
console.info:  client2 transition 3 from KEYGEN_ROUND_3 to KEYGEN_ROUND_4
console.info:  client1 transition 3 from KEYGEN_ROUND_3 to KEYGEN_ROUND_4
console.info:  client3 transition 4 from KEYGEN_ROUND_4 to KEYGEN_ROUND_5
console.info:  client1 transition 4 from KEYGEN_ROUND_4 to KEYGEN_ROUND_5
console.info:  client2 transition 4 from KEYGEN_ROUND_4 to KEYGEN_ROUND_5
console.info:  client1 transition 0 to SIGN_ROUND_0
console.info:  client2 transition 0 to SIGN_ROUND_0
console.info:  client1 transition 1 from SIGN_ROUND_0 to SIGN_ROUND_1
console.info:  client2 transition 1 from SIGN_ROUND_0 to SIGN_ROUND_1
console.info:  client1 transition 2 from SIGN_ROUND_1 to SIGN_ROUND_2
console.info:  client2 transition 2 from SIGN_ROUND_1 to SIGN_ROUND_2
console.info:  client2 transition 3 from SIGN_ROUND_2 to SIGN_ROUND_3
unhandled error: client2 undefined is not iterable (cannot read property Symbol(Symbol.iterator))


  1) tests/keygen-sign.spec.mjs:23:1 › create key shares and sign message ==========================

    Timeout of 30000ms exceeded.

    Pending operations:
      - locator.innerText at tests/keygen-sign.spec.mjs:124:49
      - locator.innerText at tests/keygen-sign.spec.mjs:124:49

    locator.innerText: Target closed
    =========================== logs ===========================
    waiting for selector ".proposal .address"
    ============================================================

        at file:///Users/muji/git/consensys/ecdsa-wasm/client/tests/keygen-sign.spec.mjs:124:49
        at file:///Users/muji/git/consensys/ecdsa-wasm/client/tests/keygen-sign.spec.mjs:123:24

  Slow test file: tests/keygen-sign.spec.mjs (30s)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    tests/keygen-sign.spec.mjs:23:1 › create key shares and sign message ===========================
```

**Comment by tmpfs** [comment]
This is due to a condition whereby calling `signProceed()` under some circumstances does not produce any messages which means the subsequent iteration of the incoming `transitionData` is not correct.

We are now catching this situation and throwing an explicit error. Attempts to recover by calling `signProceed()` again in this situation fail.

If no messages are being produced it may be possible that the previous incoming messages were not being correctly handled.

**Comment by tmpfs** [comment]
Here is a log after explicitly handling the error:

```
console.info:  client1 transition 0 to SIGN_ROUND_0
console.info:  client2 transition 0 to SIGN_ROUND_0
console.info:  client1 transition 1 from SIGN_ROUND_0 to SIGN_ROUND_1
console.info:  client2 transition 1 from SIGN_ROUND_0 to SIGN_ROUND_1
console.info:  client1 transition 2 from SIGN_ROUND_1 to SIGN_ROUND_2
console.info:  client1 Sign handle incoming {body: Object, receiver: null, round: 1, sender: 2}
console.info:  client2 transition 2 from SIGN_ROUND_1 to SIGN_ROUND_2
console.info:  client2 Sign handle incoming {body: Object, receiver: 2, round: 2, sender: 1}
unhandled error: client2 Error: Sign proceed did not generate any messages
    at Object.<anonymous> (http://localhost:3030/index.js:86796:59)
    at step (http://localhost:3030/index.js:86707:23)
    at Object.next (http://localhost:3030/index.js:86688:53)
    at fulfilled (http://localhost:3030/index.js:86679:58)
```

**Comment by tmpfs** [comment]
Debugging in the WASM shows that in this situation after handling the incoming p2p message `wants_to_proceed()` is `false`:

```
console.info:  client1 transition 0 to SIGN_ROUND_0
console.info:  client2 transition 0 to SIGN_ROUND_0
console.info:  client1 transition 1 from SIGN_ROUND_0 to SIGN_ROUND_1
console.info:  client2 transition 1 from SIGN_ROUND_0 to SIGN_ROUND_1
console.info:  client1 transition 2 from SIGN_ROUND_1 to SIGN_ROUND_2
console.info:  client1 Sign handle incoming {body: Object, receiver: null, round: 1, sender: 2}
console.log:  client1 Sign after incoming, wants_to_proceed(): true
console.info:  client2 transition 2 from SIGN_ROUND_1 to SIGN_ROUND_2
console.info:  client2 Sign handle incoming {body: Object, receiver: 2, round: 2, sender: 1}
console.log:  client2 Sign after incoming, wants_to_proceed(): false
unhandled error: client2 Error: Sign proceed did not generate any messages
    at Object.<anonymous> (http://localhost:3030/index.js:86796:59)
    at step (http://localhost:3030/index.js:86707:23)
    at Object.next (http://localhost:3030/index.js:86688:53)
    at fulfilled (http://localhost:3030/index.js:86679:58)
```

**Comment by tmpfs** [comment]
Unable to reproduce in 500 test executions since refactoring the client code, closing as likely fixed.
