### ISSUE TITLE
React error during signing (running test.sh)

### ISSUE THREAD

**Issue by tmpfs** [LavaMoat/ecdsa-wasm#48]
```
console.error:  client1 The above error occurred in the <Sign> component:

    at Sign (http://localhost:8080/index.js:86506:70)
    at Routes (http://localhost:8080/index.js:73787:5)
    at WorkerProvider (http://localhost:8080/index.js:87725:111)
    at div
    at App (http://localhost:8080/index.js:85472:72)
    at WebSocketProvider (http://localhost:8080/index.js:85412:117)
    at Router (http://localhost:8080/index.js:73721:15)
    at HashRouter (http://localhost:8080/index.js:73243:5)
    at Provider (http://localhost:8080/index.js:71131:20)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
unhandled error: client1 Cannot read properties of null (reading 'label')
unhandled error: client3 Cannot read properties of null (reading 'label')
unhandled error: client2 Cannot read properties of null (reading 'label')
console.info:  client1 [webpack-dev-server] Hot Module Replacement enabled.
console.error:  client3 The above error occurred in the <Sign> component:

    at Sign (http://localhost:8080/index.js:86506:70)
    at Routes (http://localhost:8080/index.js:73787:5)
    at WorkerProvider (http://localhost:8080/index.js:87725:111)
    at div
    at App (http://localhost:8080/index.js:85472:72)
    at WebSocketProvider (http://localhost:8080/index.js:85412:117)
    at Router (http://localhost:8080/index.js:73721:15)
    at HashRouter (http://localhost:8080/index.js:73243:5)
    at Provider (http://localhost:8080/index.js:71131:20)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
unhandled error: client3 Cannot read properties of null (reading 'label')
console.error:  client2 The above error occurred in the <Sign> component:

    at Sign (http://localhost:8080/index.js:86506:70)
    at Routes (http://localhost:8080/index.js:73787:5)
    at WorkerProvider (http://localhost:8080/index.js:87725:111)
    at div
    at App (http://localhost:8080/index.js:85472:72)
    at WebSocketProvider (http://localhost:8080/index.js:85412:117)
    at Router (http://localhost:8080/index.js:73721:15)
    at HashRouter (http://localhost:8080/index.js:73243:5)
    at Provider (http://localhost:8080/index.js:71131:20)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
unhandled error: client2 Cannot read properties of null (reading 'label')
console.info:  client3 [webpack-dev-server] Hot Module Replacement enabled.
console.info:  client2 [webpack-dev-server] Hot Module Replacement enabled.
```

**Comment by tmpfs** [comment]
Likely related to the dev server doing a hot reload:

```
console.info:  client3 transition 0 to KEYGEN_ROUND_1
console.info:  client2 transition 0 to KEYGEN_ROUND_1
console.info:  client3 transition 1 from KEYGEN_ROUND_1 to KEYGEN_ROUND_2
console.info:  client1 transition 1 from KEYGEN_ROUND_1 to KEYGEN_ROUND_2
console.info:  client2 transition 1 from KEYGEN_ROUND_1 to KEYGEN_ROUND_2
console.info:  client2 transition 2 from KEYGEN_ROUND_2 to KEYGEN_ROUND_3
console.info:  client1 transition 2 from KEYGEN_ROUND_2 to KEYGEN_ROUND_3
console.info:  client3 transition 2 from KEYGEN_ROUND_2 to KEYGEN_ROUND_3
console.info:  client1 [webpack-dev-server] App updated. Recompiling...
console.info:  client2 [webpack-dev-server] App updated. Recompiling...
console.info:  client3 [webpack-dev-server] App updated. Recompiling...
console.info:  client1 transition 3 from KEYGEN_ROUND_3 to KEYGEN_ROUND_4
console.info:  client2 transition 3 from KEYGEN_ROUND_3 to KEYGEN_ROUND_4
console.info:  client3 transition 3 from KEYGEN_ROUND_3 to KEYGEN_ROUND_4
console.info:  client2 transition 4 from KEYGEN_ROUND_4 to KEYGEN_ROUND_5
console.info:  client3 transition 4 from KEYGEN_ROUND_4 to KEYGEN_ROUND_5
console.info:  client1 transition 4 from KEYGEN_ROUND_4 to KEYGEN_ROUND_5
console.info:  client1 transition 0 to SIGN_ROUND_0
console.info:  client2 transition 0 to SIGN_ROUND_0
console.info:  client1 transition 1 from SIGN_ROUND_0 to SIGN_ROUND_1
console.info:  client2 transition 1 from SIGN_ROUND_0 to SIGN_ROUND_1
console.info:  client1 [webpack-dev-server] App hot update...
console.info:  client3 [webpack-dev-server] App hot update...
console.info:  client2 [webpack-dev-server] App hot update...
console.info:  client1 %cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools font-weight:bold
console.info:  client3 %cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools font-weight:bold
console.info:  client2 %cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools font-weight:bold
unhandled error: client1 Cannot read properties of null (reading 'label')
console.error:  client1 The above error occurred in the <Sign> component:
```

**Comment by tmpfs** [comment]
Test logic has been migrated to avoid the `webpack-dev-server`.
